# Generated by Django 2.1 on 2018-08-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_Safety', '0002_car_safety_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='complaints',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
