# Generated by Django 2.1 on 2018-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_Safety', '0003_car_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='complaints',
            field=models.CharField(default='NA', max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='front_crash_driverside_rating',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='car',
            name='front_crash_passengerside_rating',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='car',
            name='overall_front_crash_rating',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='car',
            name='overall_rating',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='car',
            name='overall_side_crash_rating',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='car',
            name='rollover_rating',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='car',
            name='safety_score',
            field=models.CharField(default='NA', max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='side_crash_driverside_rating',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='car',
            name='side_crash_passengerside_rating',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='car',
            name='side_pole_crash_rating',
            field=models.CharField(max_length=16),
        ),
    ]
