# Generated by Django 2.1 on 2018-08-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_Safety', '0004_auto_20180827_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iihs',
            name='top_safety_pick',
            field=models.CharField(max_length=8),
        ),
    ]
