# Generated by Django 2.1 on 2018-08-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_Safety', '0006_auto_20180827_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iihs',
            name='fcpr_built_after',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='fcpr_built_before',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='fcpr_qualifying_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='fcpr_rating_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='fcpr_total_points',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='frmo_built_after',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='frmo_built_before',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='frmo_overall_rating',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='frmo_qualifying_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='frso_built_after',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='frso_built_before',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='frso_overall_rating',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='frso_qualifying_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='frsop_built_after',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='frsop_built_before',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='frsop_overall_rating',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='frsop_qualifying_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='rear_built_after',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='rear_built_before',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='rear_overall_rating',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='rear_qualifying_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='rollover_built_after',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='rollover_built_before',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='rollover_overall_rating',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='rollover_qualifying_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='sr_built_after',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='sr_built_before',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='sr_overall_rating',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='sr_qualifying_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='top_safety_pick',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='tsp_built_after',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='tsp_is_qualified',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='tsp_qualifying_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iihs',
            name='tsp_year',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
