# Generated by Django 2.1 on 2018-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_Safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='safety_score',
            field=models.CharField(default='00', max_length=8),
        ),
    ]
