# Generated by Django 2.1 on 2018-08-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_Safety', '0005_auto_20180827_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iihs',
            name='tsp_is_qualified',
            field=models.CharField(max_length=8),
        ),
    ]
